
package com.duzonpay.testapi;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2018-04-19T13:29:56.614+09:00
 * Generated source version: 2.6.2
 * 
 */
public final class APIWebservice_APIWebserviceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://testapi.duzonpay.com/", "DuzonPayWebService");

    private APIWebservice_APIWebserviceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = DuzonPayWebService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        DuzonPayWebService ss = new DuzonPayWebService(wsdlURL, SERVICE_NAME);
        APIWebservice port = ss.getAPIWebserviceImplPort();  
        
        {
        System.out.println("Invoking cardBINCheckService...");
        com.duzonpay.testapi.CardBINCheckModel _cardBINCheckService_arg0 = new com.duzonpay.testapi.CardBINCheckModel();
        _cardBINCheckService_arg0.setAPIKEY("apitest1234567800001111222233330");
        _cardBINCheckService_arg0.setCARDNO("6264097890123456");
        _cardBINCheckService_arg0.setSITECD("T0060");
        com.duzonpay.testapi.CardBINCheckResult _cardBINCheckService__return = port.cardBINCheckService(_cardBINCheckService_arg0);
        System.out.println("cardBINCheckService.result=" + _cardBINCheckService__return);


        }

        System.exit(0);
    }

}
